/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/layout'
import { Route as fooRouteImport } from './routes/foo'
import { Route as barRouteImport } from './routes/bar'
import { Route as defaultRouteImport } from './routes/default'

const fooRoute = fooRouteImport.update({
  id: '/foo',
  path: '/foo',
  getParentRoute: () => rootRouteImport,
} as any)
const barRoute = barRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const defaultRoute = defaultRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof defaultRoute
  '/bar': typeof barRoute
  '/foo': typeof fooRoute
}
export interface FileRoutesByTo {
  '/': typeof defaultRoute
  '/bar': typeof barRoute
  '/foo': typeof fooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof defaultRoute
  '/bar': typeof barRoute
  '/foo': typeof fooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bar' | '/foo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bar' | '/foo'
  id: '__root__' | '/' | '/bar' | '/foo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  defaultRoute: typeof defaultRoute
  barRoute: typeof barRoute
  fooRoute: typeof fooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/foo': {
      id: '/foo'
      path: '/foo'
      fullPath: '/foo'
      preLoaderRoute: typeof fooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar': {
      id: '/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof barRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof defaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  defaultRoute: defaultRoute,
  barRoute: barRoute,
  fooRoute: fooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
